import assert from "assert";
import test from "node:test";
import { resolve } from "path";
import { generateEndpointDefinition, getParametersType, initialize } from "./core.js";

test("getParametersType()", () => {
  assert.strictEqual(getParametersType('foo'), 'unknown');
  assert.strictEqual(getParametersType('foo/bar'), 'unknown');
  assert.strictEqual(getParametersType('app/blog/[slug]'), '{\'slug\':string|typeof emptyParamSymbol}');
  assert.strictEqual(getParametersType('app/shop/[...slug]'), '{\'slug\':string[]}');
  assert.strictEqual(getParametersType('app/shop/[[...slug]]'), '{\'slug\'?:string[]}');
  assert.strictEqual(getParametersType('app/[categoryId]/[itemId]'), '{\'categoryId\':string|typeof emptyParamSymbol,\'itemId\':string|typeof emptyParamSymbol}');
});
test("generateEndpointDefinition()", () => {
  initialize(resolve("res/testbed"));
  assert.strictEqual(
    generateEndpointDefinition('api', resolve("res/testbed/app/api/route.ts")),
    `// Auto-generated by @daldalso/next-typed-route
import type { Endpoint, emptyParamSymbol } from "@daldalso/next-typed-route";
import type { NextTypedRoute } from "@daldalso/next-typed-route";
import { NextResponse } from "next/server";
declare module "@daldalso/next-typed-route"{
  export interface NextEndpointTable{
    'GET /api':Endpoint<unknown, void>;
  }
}`
  );
});