import { resolve } from "node:path";
import test from "node:test";
import { readFileSync, rmSync } from "node:fs";
import assert from "node:assert";
import type { Compiler } from "webpack";
import { NextTypesPlugin } from "next/dist/build/webpack/plugins/next-types-plugin/index.js";
import NextTypedRoutePlugin from "./plugin.js";

const plugin = new NextTypedRoutePlugin();

test("NextTypedRoutePlugin", () => {
  plugin.apply({
    context: resolve("res/testbed"),
    options: {
      name: "server",
      mode: "production",
      plugins: [
        new NextTypesPlugin({
          appDir: resolve("res/testbed/app"),
          dev: false,
          dir: resolve("res/testbed"),
          distDir: resolve("dist"),
          isEdgeServer: false,
          typedRoutes: false,
          pageExtensions: [],
          originalRedirects: undefined,
          originalRewrites: undefined
        })
      ]
    } as any
  } as Compiler);

  assert.strictEqual(
    readFileSync("res/testbed/.next/types/next-typed-route/_env.d.ts").toString(),
    [
      "// Auto-generated by @daldalso/next-typed-route",
      "declare namespace NodeJS{",
      "  export interface ProcessEnv{",
      "    FOO: string;",
      "  }",
      "}"
    ].join('\n')
  );
  rmSync(resolve("res/testbed/.next"), { recursive: true });
});

function assertFileContent(path:string, pattern:string|RegExp):void{
  const content = readFileSync(path).toString();

  if(typeof pattern === "string"){
    assert(content.includes(pattern));
  }else{
    assert(pattern.test(content));
  }
}